language:
  - c
compiler:
  - clang
  - gcc
arch:
  - amd64
  - ppc64le
  - arm64
os:
  - linux
  - osx
  - windows
script:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        cd bld
        source winenv.sh "call vcvars.bat"
        cd ..
        nmake -f "bld\w32-vcc.mk"
      ;;
      *)
        make
      ;;
    esac
