language:
  - c
compiler:
  - clang
  - gcc
arch:
  - amd64
  - ppc64le
  - arm64
os:
  - linux
  - osx
script:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        nmake -f bld\w32-vcc.mk
      ;;
      *)
        make
      ;;
    esac
